//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Myorder
    {
        public int Oid { get; set; }
        public string CompanyName { get; set; }
        public string Userid { get; set; }
        public string TUserid { get; set; }
        public string Pname { get; set; }
        public string Pquality { get; set; }
        public Nullable<int> Pcount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Payment { get; set; }
    }
}
